sudo: required
services:
  - docker

before_install:
  - docker build -t sakilahmmad71/docker-react -f Dockerfile.dev .

script:
  - docker run sakilahmmad71/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-3434237432435"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"